version: 1
external_links:
  documentation: "https://carekit-apple.github.io/CareKit/documentation/carekit/"
builder:
   configs:
   - documentation_targets: ["CareKit", "CareKitUI", "CareKitiStore", "CareKitFHIR"]
     platform: ios
   - platform: ios
     scheme: "CareKit"
   - platform: watchos
     scheme: "CareKit"
