name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  carekit-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme CareKit\ iOS -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1

  carekit-fhir:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme CareKitFHIR -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1

  carekitstore-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme CareKitStore\ iOS -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1

  carekitui-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme CareKitUI\ iOS -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1

  ockcatalog-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme OCKCatalog -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1

  ocksample-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: xcodebuild -workspace CKWorkspace.xcworkspace -scheme OCKSample -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty || exit 1
